services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booknest-app
    volumes:
      - .:/var/www # Mapeia todo o projeto Laravel para /var/www no contêiner app
    depends_on:
      - mysql

  frontend: # Nginx para o Laravel (Blade Views)
    image: nginx:alpine
    container_name: booknest-frontend
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www # <--- ADICIONE ESTA LINHA AQUI! Mapeia o projeto Laravel para /var/www no Nginx também.
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: booknest-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booknest
      MYSQL_USER: booknest_user
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: